### ISSUE TITLE
No such model 'RHSideButtons'

### ISSUE THREAD

**Issue by jaytrixz** [robertherdzik/RHSideButtons#17]
I getting this error when opening the RHSideButtonsExample.xcworkspace and running the demo project. I'm using Xcode 8.3 btw

**Comment by robertherdzik** [comment]
Hi, did you ran: 

> pod install

in example project dir?

**Comment by jaytrixz** [comment]
Hi. I did. It's still giving me the same error.

**Comment by robertherdzik** [comment]
Ok, I see 🙃. Example project should be currently fixed, please pull latest `master` and try it. Only `pod install` is required to run example project.

**Comment by jaytrixz** [comment]
It works now after doing `pod update` on the latest Xcode 8.3. Thanks a lot sir robertherdzik! 👍
