### ISSUE TITLE
Installation Section

### ISSUE THREAD

**Issue by lfarah** [robertherdzik/RHSideButtons#7]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks an ```Installation Section```
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an ```Installation Section```
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by dkhamsing** [comment]
Please update readme in order to be included on awesome-ios 

https://github.com/vsouza/awesome-ios/issues/1235

Thx

**Comment by robertherdzik** [comment]
In progress :)

**Comment by robertherdzik** [comment]
Cocoapods and installation section in Readme - Done 😊    🎉
